# -*- coding: utf-8 -*-
"""Chipotle Sales Analysis and Top Items Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127yDURQC2vDOKPc9FNfFUcZv-EoWPyrD
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load Chipotle order dataset
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
df = pd.read_csv(url, sep='\t')

df.head(50)

#Add column named total_price
df['total_price'] = df['quantity'] * df['item_price']
df.head()

#Remove the $ so the script can calculate item_price

# Check if item_price is of object (string) type before applying .str accessor
if pd.api.types.is_string_dtype(df['item_price']):
    df['item_price'] = df['item_price'].str.replace('$','', regex=False).astype('float')

#Changed the 'NaN' so the list looks clean
df = df.fillna({
    'choice_description': 'No Description'
})

df['total_price'] = df['quantity'] * df['item_price']

#Group the item_name with their item_price
ave_price = df.groupby('item_name')['total_price'].sum().reset_index()
#Isolate the top 5 selling items
top_5 = ave_price.sort_values('total_price', ascending=False).head(5)
top_5

# Draw vertical bar chart: plt.bar(x_axis, y_axis)
plt.bar(top_5['item_name'], top_5['total_price'])
plt.title('Top 5 Revenue Generators')
plt.xlabel('Item Name')
plt.ylabel('Total Price')
plt.xticks(rotation=45, ha='right') # Rotate x-axis labels


# Add numerical labels on top of the bars, rounded to 2 decimal places
for index, item_name_val in enumerate(top_5['item_name']):
    item_price_val = top_5['total_price'].iloc[index]
    plt.text(index, item_price_val + 0.5, str(round(item_price_val, 2)), ha='center', va='bottom')

plt.tight_layout() # Adjust layout to prevent labels from being cut off
# Display the chart on screen
plt.show()